src/app.py
import os
from flask import Flask, render_template
from src.common.database import Database
from src.models.users.views import user_blueprint
from src.models.stores.views import store_blueprint
from src.models.alerts.views import alert_blueprint


app = Flask(__name__)
app.config.from_object('src.config')
app.secret_key = os.environ.get('APP_SECRET_KEY')


@app.before_first_request
def init_db():
    Database.initialize()


@app.route('/')
def home():
    return render_template('home.jinja2')


app.register_blueprint(user_blueprint, url_prefix="/users")
app.register_blueprint(store_blueprint, url_prefix="/stores")
app.register_blueprint(alert_blueprint, url_prefix="/alerts")

src/models/alerts/views.py
from flask import Blueprint, request, render_template, session, redirect, url_for
from src.models.alerts.alert import Alert
from src.models.items.item import Item
import src.models.users.decorators as user_decorators


alert_blueprint = Blueprint('alerts', __name__)


@alert_blueprint.route('/new', methods=['GET', 'POST'])
@user_decorators.requires_login
def create_alert():
    if request.method == 'POST':
        name = request.form['name']
        url = request.form['url']
        price_limit = float(request.form['price_limit'])

        item = Item(name, url)
        item.save_to_mongo()

        alert = Alert(session['email'], price_limit, item._id)
        alert.load_item_price()
        return redirect(url_for('.get_alert_page', alert_id=alert._id))

    return render_template('alerts/new_alert.jinja2')


@alert_blueprint.route('/edit/<string:alert_id>', methods=['GET', 'POST'])
@user_decorators.requires_login
def edit_alert(alert_id):
    alert = Alert.find_by_id(alert_id)
    if request.method == 'POST':
        price_limit = float(request.form['price_limit'])
        alert.price_limit = price_limit
        alert.save_to_mongo()
        return redirect(url_for('users.user_alerts'))

    return render_template("alerts/edit_alert.jinja2", alert=alert)


@alert_blueprint.route('/activate/<string:alert_id>')
@user_decorators.requires_login
def activate_alert(alert_id):
    Alert.find_by_id(alert_id).activate()
    return redirect(url_for('users.user_alerts'))


@alert_blueprint.route('/deactivate/<string:alert_id>')
@user_decorators.requires_login
def deactivate_alert(alert_id):
    Alert.find_by_id(alert_id).deactivate()
    return redirect(url_for('users.user_alerts'))


@alert_blueprint.route('/delete/<string:alert_id>')
@user_decorators.requires_login
def delete_alert(alert_id):
    Alert.find_by_id(alert_id).delete()
    return redirect(url_for('users.user_alerts'))


@alert_blueprint.route('/<string:alert_id>')
@user_decorators.requires_login
def get_alert_page(alert_id):
    return render_template('alerts/alert.jinja2', alert=Alert.find_by_id(alert_id))


@alert_blueprint.route('/check_price/<string:alert_id>')
def check_alert_price(alert_id):
    Alert.find_by_id(alert_id).load_item_price()
    return redirect(url_for('.get_alert_page', alert_id=alert_id))

src/models/stores/views.py
import json
from flask import Blueprint, render_template, request, redirect, url_for
from src.models.stores.store import Store
import src.models.users.decorators as user_decorators


store_blueprint = Blueprint('stores', __name__)


@store_blueprint.route('/')
def index():
    stores = Store.all()
    return render_template('stores/store_index.jinja2', stores=stores)


@store_blueprint.route('/store/<string:store_id>')
def store_page(store_id):
    return render_template('stores/store.jinja2', store=Store.get_by_id(store_id))


@store_blueprint.route('/edit/<string:store_id>', methods=['GET', 'POST'])
@user_decorators.requires_admin_permissions
def edit_store(store_id):
    store = Store.get_by_id(store_id)
    if request.method == 'POST':
        name = request.form['name']
        url_prefix = request.form['url_prefix']
        tag_name = request.form['tag_name']
        query = json.loads(request.form['query'])
        tag_name2 = request.form['tag_name2']
        query2 = json.loads(request.form['query2'])

        store.name = name
        store.url_prefix = url_prefix
        store.tag_name = tag_name
        store.query = query
        store.tag_name2 = tag_name2
        store.query2 = query2

        store.save_to_mongo()
        return redirect(url_for('.index'))

    return render_template('stores/edit_store.jinja2', store=store)


@store_blueprint.route('/delete/<string:store_id>')
@user_decorators.requires_admin_permissions
def delete_store(store_id):
    Store.get_by_id(store_id).delete()
    return redirect(url_for('.index'))


@store_blueprint.route('/new', methods=['GET', 'POST'])
@user_decorators.requires_admin_permissions
def create_store():
    if request.method == 'POST':
        name = request.form['name']
        url_prefix = request.form['url_prefix']
        tag_name = request.form['tag_name']
        query = json.loads(request.form['query'])
        tag_name2 = request.form['tag_name2']
        query2 = json.loads(request.form['query2'])

        Store(name, url_prefix, tag_name, query, tag_name2, query2).save_to_mongo()
        return redirect(url_for('.index'))

    return render_template('stores/new_store.jinja2')

src/models/users/views.py
from flask import Blueprint, request, session, redirect, url_for, render_template
import src.models.users.errors as UserErrors
from src.models.users.decorators import requires_login
from src.models.users.user import User


user_blueprint = Blueprint('users', __name__)


@user_blueprint.route('/login', methods=['GET', 'POST'])
def login_user():
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']

        try:
            if User.is_login_valid(email, password):
                session['email'] = email
                return redirect(url_for(".user_alerts"))
        except UserErrors.UserError as e:
            return e.message

    return render_template("users/login.jinja2")


@user_blueprint.route('/register', methods=['GET', 'POST'])
def register_user():
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']

        try:
            if User.register_user(email, password):
                session['email'] = email
                return redirect(url_for(".user_alerts"))
        except UserErrors.UserError as e:
            return e.message

    return render_template("users/register.jinja2")


@user_blueprint.route('/alerts')
@requires_login
def user_alerts():
    user = User.find_by_email(session['email'])
    return render_template("users/alerts.jinja2", alerts=user.get_alerts())


@user_blueprint.route('/logout')
def logout_user():
    session['email'] = None
    return redirect(url_for('home'))

src/templates/alerts/alert.jinja2
{% extends "base.jinja2" %}
{% block content %}
<h1>{{ alert.item.name }}</h1><br>
<div class="panel">
    <p>Your budget: <strong>{{ alert.price_limit }}</strong></p>
    <p>Last price found: <strong>{{ alert.item.price }}</strong></p>
    <p>Last checked on: <strong>{{ alert.last_checked.strftime('%d-%m-%Y at %H:%M') }}</strong></p>
    <a class="btn btn-default btn-alert" href="{{ alert.item.url }}" role="button">View Game On Steam</a>
    <a class="btn btn-success btn-alert" href="{{ url_for('alerts.check_alert_price', alert_id=alert._id) }}" role="button">Update Price Manually</a>
    <br>
    <a class="btn btn-warning btn-alert" href="{{ url_for('alerts.edit_alert', alert_id=alert._id) }}" role="button">Edit</a>
    {% if alert.active %}
        <a class="btn btn-danger btn-alert" href="{{ url_for('alerts.deactivate_alert', alert_id=alert._id) }}" role="button">Deactivate</a>
    {% else %}
        <a class="btn btn-info btn-alert" href="{{ url_for('alerts.activate_alert', alert_id=alert._id) }}" role="button">Activate</a>
        <a class="btn btn-danger btn-alert" href="{{ url_for('alerts.delete_alert', alert_id=alert._id) }}" role="button">Delete</a>
    {% endif %}
</div>
<h4><a href="{{ url_for('users.user_alerts') }}" title="Your Alerts"><span class="glyphicon glyphicon-chevron-left"></span> Go back</a></h4>
{% endblock %}

src/templates/alerts/edit_alert.jinja2
{% extends "base.jinja2" %}
{% block content %}
<h1>Edit Alert</h1><br>
<div class="form-size">
    <form method="post">
        <div class="form-group">
            <label for="name">Alert Name</label>
            <input type="text" class="form-control" id="name" name="name" placeholder="{{ alert.item.name }}" disabled>
        </div>
        <div class="form-group">
            <label for="url">URL</label>
            <input type="text" class="form-control" id="url" name="url" placeholder="{{ alert.item.url }}" disabled>
        </div>
        <div class="form-group">
            <label for="price_limit">Alert Price Limit</label>
            <input type="text" class="form-control" id="price_limit" name="price_limit" placeholder="45.0" value="{{ alert.price_limit }}" aria-describedby="priceLimitBlock">
            <p id="priceLimitBlock" class="help-block">You will get an email when the price goes under this amount.</p>
        </div>
        <button type="submit" class="btn btn-warning">Update</button>
    </form>
</div>
<h4><a href="{{ url_for('users.user_alerts') }}" title="Your Alerts"><span class="glyphicon glyphicon-chevron-left"></span> Go back</a></h4>
{% endblock %}

src/templates/alerts/new_alert.jinja2
{% extends "base.jinja2" %}
{% block content %}
<h1>Create Alert</h1><br>
<div class="form-size">
    <form method="post">
        <div class="form-group">
            <label for="name">Alert Name</label>
            <input type="text" class="form-control" id="name" name="name" placeholder="Name">
        </div>
        <div class="form-group">
            <label for="url">URL</label>
            <input type="text" class="form-control" id="url" name="url" placeholder="http://...">
        </div>
        <div class="form-group">
            <label for="price_limit">Alert Price Limit</label>
            <input type="text" class="form-control" id="price_limit" name="price_limit" placeholder="45.0" aria-describedby="priceLimitBlock">
            <p id="priceLimitBlock" class="help-block">We'll send you an email when the price reaches or goes under this amount.</p>
        </div>
        <button type="submit" class="btn btn-info">Create</button>
    </form>
</div>
<h4><a href="{{ url_for('users.user_alerts') }}" title="Your Alerts"><span class="glyphicon glyphicon-chevron-left"></span> Go back</a></h4>
{% endblock %}

src/templates/base.jinja2
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Steam Sale Alerts</title>
    {% include 'html_dependencies.jinja2' %}
</head>
<body>
<nav class="navbar navbar-default" role="navigation">
     <div class="container">
         <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapsed" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="https://store.steampowered.com/mobile" title="Steam">Browse Steam</a>
        </div>
        <div id="navbar-collapsed" class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
                {% if session['email'] %}
                    <li><a href="{{ url_for('users.user_alerts') }}" title="Your Alerts"><span class="glyphicon glyphicon-bell"></span> Alerts</a></li>
                    <li><a href="{{ url_for('users.logout_user') }}" title="Log Out"><span class="glyphicon glyphicon-log-out"></span> Log Out</a></li>
                {% else %}
                    <li><a href="{{ url_for('users.register_user') }}" title="Sign up"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
                    <li><a href="{{ url_for('users.login_user') }}" title="Log in"><span class="glyphicon glyphicon-log-in"></span> Log In</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
<div class="content container">
    {% block content %}

    {% endblock %}
</div>
</body>
</html>

src/templates/home.jinja2
{% extends "base.jinja2" %}
{% block content %}
<h2><strong>Steam Sale Alerts<br></strong></h2>
<div class="jumbotron">
    <ol>
        <li>Click 'Create new alert'.</li>
        <li>Enter the link to a game's Steam page.</li>
        <li>Choose your budget.</li>
        <li>You're done!</li>
    </ol>
    <p>As soon as a game is within your budget we'll immediately notify you via email,
        so you will always be the first to know. Sign up and get started right away!</p>
    <a class="btn btn-default btn-lg" href="{{ url_for('users.register_user') }}" role="button">Sign Up</a>
    <a class="btn btn-default btn-lg" href="{{ url_for('users.login_user') }}" role="button">Log in</a>
</div>
{% endblock %}

src/templates/html_dependencies.jinja2
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
<script src="http://code.jquery.com/jquery-2.2.0.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
<link rel="stylesheet" type="text/css" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">

src/templates/stores/edit_store.jinja2
{% extends "base.jinja2" %}
{% block content %}
    <div class="page-header">
        <h1>Edit Store</h1>
    </div>
    <div class="form-size">
        <form method="post">
            <div class="form-group">
                <label for="name">Store Name</label>
                <input type="text" class="form-control" id="name" name="name" placeholder="Store Name" value="{{ store.name }}">
            </div>
            <div class="form-group">
                <label for="url_prefix">Store URL Prefix</label>
                <input type="text" class="form-control" id="url_prefix" name="url_prefix" placeholder="http://..." value="{{ store.url_prefix }}" aria-describedby="storeURLPrefixHelp">
                <span id="storeURLPrefixHelp" class="help-block">What characters do all URLs in this store start with? (e.g. http://www.amazon.com)</span>
            </div>
            <div class="form-group">
                <label for="tag_name">Tag Name</label>
                <input type="text" class="form-control" id="tag_name" name="tag_name" placeholder="span" value="{{ store.tag_name }}" aria-describedby="storeTagNameHelp">
                <span id="storeTagNameHelp" class="help-block">What is the HTML tag of the item that contains the item price? (usually <code>span</code>)</span>
            </div>
            <div class="form-group">
                <label for="query">Search query</label>
                <input type="text" class="form-control" id="query" name="query" placeholder='{"id": "price-now"}' value='{{ store.query | tojson }}' aria-describedby="queryHelp">
                <span id="queryHelp" class="help-block">What JSON query would we have to do to find the specific tag that contains the item price? Remember to use double quotes(" ").</span>
            </div>
            <div class="form-group">
                <label for="tag_name">Tag Name 2</label>
                <input type="text" class="form-control" id="tag_name2" name="tag_name2" placeholder="span" value="{{ store.tag_name2 }}" aria-describedby="storeTagNameHelp2">
                <span id="storeTagNameHelp2" class="help-block">What is the HTML tag of the item that contains the item price? (usually <code>span</code>)</span>
            </div>
            <div class="form-group">
                <label for="query">Search query 2</label>
                <input type="text" class="form-control" id="query2" name="query2" placeholder='{"id": "price-now"}' value='{{ store.query2 | tojson }}' aria-describedby="queryHelp2">
                <span id="queryHelp2" class="help-block">What JSON query would we have to do to find the specific tag that contains the item price? Remember to use double quotes(" ").</span>
            </div>
            <button type="submit" class="btn btn-warning">Update</button>
        </form>
    </div>
{% endblock %}

src/templates/stores/new_store.jinja2
{% extends "base.jinja2" %}
{% block content %}
    <div class="page-header">
        <h1>Create Store</h1>
    </div>
    <div class="form-size">
        <form method="post">
            <div class="form-group">
                <label for="name">Store Name</label>
                <input type="text" class="form-control" id="name" name="name" placeholder="Store Name">
            </div>
            <div class="form-group">
                <label for="url_prefix">Store URL Prefix</label>
                <input type="text" class="form-control" id="url_prefix" name="url_prefix" placeholder="http://..." aria-describedby="storeURLPrefixHelp">
                <span id="storeURLPrefixHelp" class="help-block">What characters do all URLs in this store start with? (e.g. http://www.amazon.com)</span>
            </div>
            <div class="form-group">
                <label for="tag_name">Tag Name</label>
                <input type="text" class="form-control" id="tag_name" name="tag_name" placeholder="span" value="span" aria-describedby="storeTagNameHelp">
                <span id="storeTagNameHelp" class="help-block">What is the HTML tag of the item that contains the item price? (usually <code>span</code>)</span>
            </div>
            <div class="form-group">
                <label for="query">Search query</label>
                <input type="text" class="form-control" id="query" name="query" placeholder='{"id": "price-now"}' value='{"id": "price"}' aria-describedby="queryHelp">
                <span id="queryHelp" class="help-block">What JSON query would we have to do to find the specific tag that contains the item price? Remember to use double quotes(" ").</span>
            </div>
            <div class="form-group">
                <label for="tag_name2">Tag Name 2</label>
                <input type="text" class="form-control" id="tag_name2" name="tag_name2" placeholder="span" value="span" aria-describedby="storeTagNameHelp">
                <span id="storeTagNameHelp2" class="help-block">What is the HTML tag of the item that contains the item price? (usually <code>span</code>)</span>
            </div>
            <div class="form-group">
                <label for="query2">Search query 2</label>
                <input type="text" class="form-control" id="query2" name="query2" placeholder='{"id": "price-now"}' value='{"id": "price"}' aria-describedby="queryHelp">
                <span id="queryHelp2" class="help-block">What JSON query would we have to do to find the specific tag that contains the item price? Remember to use double quotes(" ").</span>
            </div>
            <button type="submit" class="btn btn-default">Create</button>
        </form>
    </div>
{% endblock %}

src/templates/stores/store.jinja2
{% extends "base.jinja2" %}
{% block content %}
<div class="page-header">
    <h1>Stores
        <small>{{ store.name }}</small>
    </h1>
</div>
<p>All URLs in this store should start with <strong>{{ store.url_prefix }}</strong></p>
{% if session['email'] in config.ADMINS %}
<div class="panel panel-default">
    <div class="panel-body">
        <a class="btn btn-warning" href="{{ url_for('stores.edit_store', store_id=store._id) }}" role="button">Edit store</a>
        <a class="btn btn-danger" href="{{ url_for('stores.delete_store', store_id=store._id) }}" role="button">Permanently delete store</a>
    </div>
</div>
{% endif %}
{% endblock %}

src/templates/stores/store_index.jinja2
{% extends "base.jinja2" %}
{% block content %}
    <div class="page-header">
        <h1>Stores <small>list of supported stores</small></h1>
    </div>
    <div class="list-group">
        {% for store in stores %}
            <a href="{{ url_for('stores.store_page', store_id=store._id) }}" class="list-group-item">
                <h4 class="title">{{ store.name }}</h4>
                <p class="list-group-item-text">
                    All URLs in this store should start with <strong>{{ store.url_prefix }}</strong>
                </p>
            </a>
        {% endfor %}
    </div>
    {% if session['email'] in config.ADMINS %}
        <a class="btn btn-success" href="{{ url_for('stores.create_store') }}">
            <span class="glyphicon glyphicon-plus"></span> Create New
        </a>
    {% endif %}
{% endblock %}

src/templates/users/alerts.jinja2
{% extends "base.jinja2" %}
{% block content %}
<h1>Alerts</h1><br>
    <div class="list-group">
        {% for alert in alerts %}
            <a href="/alerts/{{ alert._id }}" class="list-group-item {{ 'list-group-item-warning' if not alert.active else '' }}">
                <h3 class="list-group-item-heading">
                    {{ '<span class="glyphicon glyphicon-pause"></span>' if not alert.active else '' }}<u>{{ alert.item.name }}</u>
                </h3>
                <p class="list-group-item-text">Your budget: <strong>{{ alert.price_limit }}</strong></p>
                <p class="list-group-item-text">Last price found: <strong>{{ alert.item.price }}</strong></p>
                <p class="list-group-item-text">Last checked on: <strong>{{ alert.last_checked.strftime("%d-%m-%Y %H:%M") }}</strong></p>
            </a>
        {% endfor %}
    </div>
<a class="btn btn-info" href="{{ url_for('alerts.create_alert') }}"><strong>Create New</strong></a>
{% endblock %}

src/templates/users/login.jinja2
{% extends "base.jinja2" %}
{% block content %}
    <div class="form-size">
        <form action="{{ url_for('users.login_user') }}" method="post">
            <div class="form-group">
                <label for="email">Email address</label>
                <input type="email" class="form-control" id="email" name="email" placeholder="Email">
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" class="form-control" id="password" name="password" placeholder="********">
            </div>
            <button type="submit" class="btn btn-default">Log In</button>
        </form>
    </div>
{% endblock %}

src/templates/users/login2.jinja2
{% extends "base.jinja2" %}
{% block content %}
<h2>Wrong password</h2>
    <div class="form-size">
        <form action="{{ url_for('users.login_user') }}" method="post">
            <div class="form-group">
                <label for="email">Email address</label>
                <input type="email" class="form-control" id="email" name="email" placeholder="Email">
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" class="form-control" id="password" name="password" placeholder="********">
            </div>
            <button type="submit" class="btn btn-default">Log In</button>
        </form>
    </div>
{% endblock %}

src/templates/users/register.jinja2
{% extends "base.jinja2" %}
{% block content %}
    <div class="form-size">
        <form action="{{ url_for('users.register_user') }}" method="post">
            <div class="form-group">
                <label for="email">Email address</label>
                <input type="email" class="form-control" id="email" name="email" placeholder="Email">
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" class="form-control" id="password" name="password" placeholder="********">
            </div>
            <button type="submit" class="btn btn-default">Sign Up</button>
        </form>
    </div>
{% endblock %}

src/templates/users/register2.jinja2
{% extends "base.jinja2" %}
{% block content %}
    <div class="form-size">
        <form action="{{ url_for('users.register_user') }}" method="post">
            <div class="form-group">
                <label for="email">Email address</label>
                <input type="email" class="form-control" id="email" name="email" placeholder="Email">
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" class="form-control" id="password" name="password" placeholder="********">
            </div>
            <button type="submit" class="btn btn-default">Sign Up</button>
        </form>
    </div>
{% endblock %}